export const DEFAULT_PRODUCTS = [
  // ========== Restaurant Sabor Peruano - San Martin de Porres (5 platos) ==========
  {
    id: "rsp1",
    name: "Lomo Saltado",
    description: "Clásico peruano con lomo de res, papas y arroz.",
    price: 8.90,
    originalPrice: 22.00,
    category: "Comidas",
    image: "https://i.ytimg.com/vi/ErRIA_Owc58/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCZHq6bDGR9KRIWFxTMjA5QU2p9Jw",
    district: "San Martin de Porres",
    businessName: "Restaurant Sabor Peruano",
    expiresInHours: 3 // Vence en 3 horas
  },
  {
    id: "rsp2",
    name: "Ají de Gallina",
    description: "Cremoso ají de gallina con papas y arroz. Preparado hoy.",
    price: 7.50,
    originalPrice: 20.00,
    category: "Comidas",
    image: "https://www.gourmet.cl/wp-content/uploads/2016/09/Aji-gallina.jpg",
    district: "San Martin de Porres",
    businessName: "Restaurant Sabor Peruano",
    expiresInHours: 5 // Vence en 5 horas
  },
  {
    id: "rsp3",
    name: "Arroz con Pollo",
    description: "Arroz verde con pollo jugoso y ensalada. Del almuerzo.",
    price: 6.90,
    originalPrice: 18.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_tfdTXsBnCJ63QuDZaYqCDh3Y2QPSZE3h6w&s",
    district: "San Martin de Porres",
    businessName: "Restaurant Sabor Peruano",
    expiresInHours: 4 // Vence en 4 horas
  },
  {
    id: "rsp4",
    name: "Seco de Res",
    description: "Seco de res con frejoles y yuca. Especialidad de la casa.",
    price: 9.50,
    originalPrice: 24.00,
    category: "Comidas",
    image: "https://static.wixstatic.com/media/9755d8_88b4827650f44340bc5319757f45d8f7~mv2.png/v1/fill/w_1000,h_563,al_c,q_90,usm_0.66_1.00_0.01/9755d8_88b4827650f44340bc5319757f45d8f7~mv2.png",
    district: "San Martin de Porres",
    businessName: "Restaurant Sabor Peruano",
    expiresInHours: 6 // Vence en 6 horas
  },
  {
    id: "rsp5",
    name: "Chicharrón de Pollo",
    description: "Pollo crocante con camote y salsa criolla.",
    price: 8.00,
    originalPrice: 19.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=1200&auto=format&fit=crop",
    district: "San Martin de Porres",
    businessName: "Restaurant Sabor Peruano",
    expiresInHours: 2 // Vence en 2 horas - URGENTE
  },
  
  // ========== Pollería Don Pepe - Comas (6 platos) ==========
  {
    id: "pdp1",
    name: "Pollo a la Brasa (1/4)",
    description: "Cuarto de pollo jugoso con papas fritas.",
    price: 7.50,
    originalPrice: 18.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?q=80&w=1200&auto=format&fit=crop",
    district: "Comas",
    businessName: "Pollería Don Pepe",
    expiresInHours: 2 // Vence en 2 horas
  },
  {
    id: "pdp2",
    name: "Pollo a la Brasa (1/2)",
    description: "Medio pollo con papas y ensalada. Preparado hoy.",
    price: 13.90,
    originalPrice: 32.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?q=80&w=1200&auto=format&fit=crop",
    district: "Comas",
    businessName: "Pollería Don Pepe",
    expiresInHours: 4 // Vence en 4 horas
  },
  {
    id: "pdp3",
    name: "Alitas BBQ (12 unidades)",
    description: "Alitas de pollo bañadas en salsa BBQ. Cierre de turno.",
    price: 9.90,
    originalPrice: 24.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?q=80&w=1200&auto=format&fit=crop",
    district: "Comas",
    businessName: "Pollería Don Pepe",
    expiresInHours: 1 // Vence en 1 hora - MUY URGENTE
  },
  {
    id: "pdp4",
    name: "Salchipapas Premium",
    description: "Papas fritas con salchicha y salsas variadas.",
    price: 5.90,
    originalPrice: 14.00,
    category: "Comidas",
    image: "https://img.freepik.com/fotos-premium/salchipapa-comida-callejera-tradicional-salchipapas-peru-salchichas-papas-fritas_492434-134.jpg",
    district: "Comas",
    businessName: "Pollería Don Pepe",
    expiresInHours: 3
  },
  {
    id: "pdp5",
    name: "Broaster Criollo",
    description: "Pollo broaster con papas y ensalada criolla. Del almuerzo.",
    price: 8.50,
    originalPrice: 20.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?q=80&w=1200&auto=format&fit=crop",
    district: "Comas",
    businessName: "Pollería Don Pepe",
    expiresInHours: 5
  },
  {
    id: "pdp6",
    name: "Nuggets con Papas",
    description: "Nuggets de pollo crujientes con papas fritas. Para niños.",
    price: 6.50,
    originalPrice: 15.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdxwkJysqK9z3iNFx9Ojw8klcYQBZtn1NyOw&s",
    district: "Comas",
    businessName: "Pollería Don Pepe",
    expiresInHours: 4
  },
  
  // ========== Ohashi Sushi Bar - Los Olivos (7 platos) ==========
  {
    id: "osb1",
    name: "Sushi Roll Tempura",
    description: "Roll especial con tempura crujiente. Preparado hoy en la mañana.",
    price: 10.90,
    originalPrice: 28.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmylAf791ehsCstrYVrR8XTTdlw0AEze_JFQ&s",
    district: "Los Olivos",
    businessName: "Ohashi Sushi Bar",
    expiresInHours: 4
  },
  {
    id: "osb2",
    name: "Sashimi Mixto",
    description: "Selección de pescado fresco en láminas. Del día.",
    price: 15.90,
    originalPrice: 38.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqg5gjjK2sKvP6SBFwElUnirnZq1tRXTxOWw&s",
    district: "Los Olivos",
    businessName: "Ohashi Sushi Bar",
    expiresInHours: 2
  },
  {
    id: "osb3",
    name: "California Roll",
    description: "Roll de cangrejo, palta y pepino. Fresco del día.",
    price: 9.50,
    originalPrice: 24.00,
    category: "Comidas",
    image: "https://simmerandsage.com/wp-content/uploads/2023/09/Crunchy-California-Roll1.jpg",
    district: "Los Olivos",
    businessName: "Ohashi Sushi Bar",
    expiresInHours: 5
  },
  {
    id: "osb4",
    name: "Yakimeshi",
    description: "Arroz frito japonés con verduras y camarones. Recién preparado.",
    price: 8.90,
    originalPrice: 22.00,
    category: "Comidas",
    image: "https://cdn7.recetasdeescandalo.com/wp-content/uploads/2020/06/Receta-de-yakimeshi-o-arroz-frito-al-estilo-japones-con-pollo-y-verduras.jpg",
    district: "Los Olivos",
    businessName: "Ohashi Sushi Bar",
    expiresInHours: 3
  },
  {
    id: "osb5",
    name: "Gyozas (8 unidades)",
    description: "Empanadillas japonesas rellenas de cerdo. Cierre de turno.",
    price: 7.50,
    originalPrice: 18.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=1200&auto=format&fit=crop",
    district: "Los Olivos",
    businessName: "Ohashi Sushi Bar",
    expiresInHours: 2
  },
  {
    id: "osb6",
    name: "Ramen Miso",
    description: "Sopa japonesa con fideos, huevo y cerdo. Preparado hoy.",
    price: 11.90,
    originalPrice: 28.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?q=80&w=1200&auto=format&fit=crop",
    district: "Los Olivos",
    businessName: "Ohashi Sushi Bar",
    expiresInHours: 4
  },
  {
    id: "osb7",
    name: "Edamame",
    description: "Vainas de soja al vapor con sal. Entrada fresca.",
    price: 4.50,
    originalPrice: 10.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFlKngKbDGI4WkanLAAV5LHfL6eUrtxa4urA&s",
    district: "Los Olivos",
    businessName: "Ohashi Sushi Bar",
    expiresInHours: 6
  },
  
  // ========== Chifa Lung Fung - Independencia (6 platos) ==========
  {
    id: "clf1",
    name: "Arroz Chaufa Especial",
    description: "Chaufa de pollo y cerdo al estilo chifa.",
    price: 6.90,
    originalPrice: 16.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRecJGRDME6Ce55P5AolTXbjM8X_OCh8z1nHA&s",
    district: "Independencia",
    businessName: "Chifa Lung Fung",
    expiresInHours: 3
  },
  {
    id: "clf2",
    name: "Tallarín Saltado",
    description: "Tallarines con pollo y verduras salteadas. Del almuerzo.",
    price: 7.50,
    originalPrice: 18.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBz5sgja8ql126z8TPz5EfOS5bG77x9GO-4A&s",
    district: "Independencia",
    businessName: "Chifa Lung Fung",
    expiresInHours: 5
  },
  {
    id: "clf3",
    name: "Wantán Frito (10 unidades)",
    description: "Wantanes crujientes con salsa agridulce. Recién hechos.",
    price: 8.90,
    originalPrice: 20.00,
    category: "Comidas",
    image: "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/CA243SOL5ZHP3CKYNAXXXAZTNA.jpg",
    district: "Independencia",
    businessName: "Chifa Lung Fung",
    expiresInHours: 2
  },
  {
    id: "clf4",
    name: "Aeropuerto",
    description: "Combinación de arroz chaufa y tallarín saltado. Especialidad.",
    price: 9.50,
    originalPrice: 24.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?q=80&w=1200&auto=format&fit=crop",
    district: "Independencia",
    businessName: "Chifa Lung Fung",
    expiresInHours: 4
  },
  {
    id: "clf5",
    name: "Pollo Tipakay",
    description: "Pollo en trozos con verduras y salsa especial. Del día.",
    price: 8.50,
    originalPrice: 21.00,
    category: "Comidas",
    image: "https://img-global.cpcdn.com/recipes/819cb89210d39293/1200x630cq80/photo.jpg",
    district: "Independencia",
    businessName: "Chifa Lung Fung",
    expiresInHours: 6
  },
  {
    id: "clf6",
    name: "Sopa Wantán",
    description: "Sopa china con wantanes y verduras. Caliente y reconfortante.",
    price: 7.90,
    originalPrice: 18.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTja_KKgwjshSsVGuLPzJ0Cdda4-lrAzhFdJA&s",
    district: "Independencia",
    businessName: "Chifa Lung Fung",
    expiresInHours: 4
  },
  
  // ========== Pizzería La Nonna - San Juan de Miraflores (5 platos) ==========
  {
    id: "pln1",
    name: "Pizza Familiar Hawaiana",
    description: "Pizza grande con piña y jamón. Del día de ayer.",
    price: 12.00,
    originalPrice: 35.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200&auto=format&fit=crop",
    district: "San Juan de Miraflores",
    businessName: "Pizzería La Nonna",
    expiresInHours: 8
  },
  {
    id: "pln2",
    name: "Pizza Pepperoni Mediana",
    description: "Pizza con extra pepperoni y queso. Horneada hoy.",
    price: 9.90,
    originalPrice: 25.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=1200&auto=format&fit=crop",
    district: "San Juan de Miraflores",
    businessName: "Pizzería La Nonna",
    expiresInHours: 5
  },
  {
    id: "pln3",
    name: "Pizza Margherita",
    description: "Pizza clásica con albahaca fresca y mozzarella. Del día.",
    price: 8.50,
    originalPrice: 22.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1200&auto=format&fit=crop",
    district: "San Juan de Miraflores",
    businessName: "Pizzería La Nonna",
    expiresInHours: 6
  },
  {
    id: "pln4",
    name: "Lasagna Boloñesa",
    description: "Lasagna con carne molida y salsa bechamel. Preparada hoy.",
    price: 10.90,
    originalPrice: 26.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?q=80&w=1200&auto=format&fit=crop",
    district: "San Juan de Miraflores",
    businessName: "Pizzería La Nonna",
    expiresInHours: 7
  },
  {
    id: "pln5",
    name: "Calzone de Jamón y Queso",
    description: "Pizza doblada rellena de jamón y queso. Recién horneada.",
    price: 7.90,
    originalPrice: 19.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1200&auto=format&fit=crop",
    district: "San Juan de Miraflores",
    businessName: "Pizzería La Nonna",
    expiresInHours: 3
  },
  
  // ========== Cevichería El Puerto - Villa el Salvador (6 platos) ==========
  {
    id: "cep1",
    name: "Ceviche Mixto",
    description: "Fresco ceviche con pescado y mariscos.",
    price: 9.90,
    originalPrice: 25.00,
    category: "Comidas",
    image: "https://www.ajinomoto.com.pe:8085/img/receta/230.-Cebiche-mixto.jpg",
    district: "Villa el Salvador",
    businessName: "Cevichería El Puerto",
    expiresInHours: 4
  },
  {
    id: "cep2",
    name: "Ceviche de Pescado",
    description: "Ceviche clásico de pescado blanco. Del día.",
    price: 8.50,
    originalPrice: 22.00,
    category: "Comidas",
    image: "https://jameaperu.com/assets/images/ceviche-de-pescado_800x534.webp",
    district: "Villa el Salvador",
    businessName: "Cevichería El Puerto",
    expiresInHours: 3
  },
  {
    id: "cep3",
    name: "Arroz con Mariscos",
    description: "Arroz amarillo con mariscos frescos. Preparado hoy.",
    price: 11.90,
    originalPrice: 28.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQymEbCgN4BDoMdFlvp_V8T9DlKUMft8oP2mQ&s",
    district: "Villa el Salvador",
    businessName: "Cevichería El Puerto",
    expiresInHours: 5
  },
  {
    id: "cep4",
    name: "Chicharrón de Calamar",
    description: "Calamares fritos crujientes con salsa tártara. Recién hecho.",
    price: 10.50,
    originalPrice: 24.00,
    category: "Comidas",
    image: "https://i.ytimg.com/vi/MZwro2DS77M/maxresdefault.jpg",
    district: "Villa el Salvador",
    businessName: "Cevichería El Puerto",
    expiresInHours: 2
  },
  {
    id: "cep5",
    name: "Jalea Mixta",
    description: "Pescado y mariscos fritos con yuca. Especialidad de la casa.",
    price: 13.90,
    originalPrice: 32.00,
    category: "Comidas",
    image: "https://comedera.com/wp-content/uploads/sites/9/2022/06/jalea-mixta.jpg",
    district: "Villa el Salvador",
    businessName: "Cevichería El Puerto",
    expiresInHours: 3
  },
  {
    id: "cep6",
    name: "Leche de Tigre",
    description: "Jugo de ceviche con trozos de pescado. Energizante.",
    price: 6.50,
    originalPrice: 15.00,
    category: "Bebidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp2bbjDxKtXS9Bhztm9GB7lqpmONqoLcAy5w&s",
    district: "Villa el Salvador",
    businessName: "Cevichería El Puerto",
    expiresInHours: 2
  },
  
  // ========== Pastelería Dulce Arte - Chorrillos (7 platos) ==========
  {
    id: "pda1",
    name: "Tarta de Maracuyá",
    description: "Postre casero con toque ácido y cremoso. Hecho ayer.",
    price: 5.50,
    originalPrice: 12.00,
    category: "Postres",
    image: "https://www.elespectador.com/resizer/v2/JPTLRDZEJBCXRJBUXDJLMSPY2Q.jpg?auth=b32e2fc587756a1d99ab36cad2d53234486018f96fd11acd223c90edb484a223&width=920&height=613&smart=true&quality=60",
    district: "Chorrillos",
    businessName: "Pastelería Dulce Arte",
    expiresInHours: 12
  },
  {
    id: "pda2",
    name: "Cheesecake de Fresa",
    description: "Suave cheesecake con topping de fresas. Del día anterior.",
    price: 6.50,
    originalPrice: 15.00,
    category: "Postres",
    image: "https://www.recetasnestlecam.com/sites/default/files/srh_recipes/07892f02f7c57b83d5703b4ee924221e.jpg",
    district: "Chorrillos",
    businessName: "Pastelería Dulce Arte",
    expiresInHours: 10
  },
  {
    id: "pda3",
    name: "Torta de Chocolate",
    description: "Húmeda torta de chocolate con ganache. Hecha ayer.",
    price: 7.90,
    originalPrice: 18.00,
    category: "Postres",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=1200&auto=format&fit=crop",
    district: "Chorrillos",
    businessName: "Pastelería Dulce Arte",
    expiresInHours: 14
  },
  {
    id: "pda4",
    name: "Alfajores (6 unidades)",
    description: "Alfajores rellenos de dulce de leche. Del día anterior.",
    price: 4.50,
    originalPrice: 10.00,
    category: "Postres",
    image: "https://hispanaglobal.com/wp-content/uploads/2022/03/Dulce-De-Leche-cookies-9-scaled.jpg",
    district: "Chorrillos",
    businessName: "Pastelería Dulce Arte",
    expiresInHours: 8
  },
  {
    id: "pda5",
    name: "Suspiro Limeño",
    description: "Postre tradicional peruano con dulce de leche y merengue. Hecho ayer.",
    price: 4.50,
    originalPrice: 10.00,
    category: "Postres",
    image: "https://portal.andina.pe/EDPfotografia2/Thumbnail/2008/05/17/000062608W.jpg",
    district: "Chorrillos",
    businessName: "Pastelería Dulce Arte",
    expiresInHours: 10
  },
  {
    id: "pda6",
    name: "Pie de Limón",
    description: "Refrescante pie con crema de limón. Del día.",
    price: 5.90,
    originalPrice: 13.00,
    category: "Postres",
    image: "https://www.recetasnestle.com.ec/sites/default/files/srh_recipes/4216cb5b181b75dea1062cb02762a963.jpg",
    district: "Chorrillos",
    businessName: "Pastelería Dulce Arte",
    expiresInHours: 6
  },
  {
    id: "pda7",
    name: "Brownies (4 unidades)",
    description: "Brownies de chocolate con nueces. Horneados ayer.",
    price: 3.90,
    originalPrice: 9.00,
    category: "Postres",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=1200&auto=format&fit=crop",
    district: "Chorrillos",
    businessName: "Pastelería Dulce Arte",
    expiresInHours: 9
  },
  
  // ========== Panadería San José - El Agustino (5 platos) ==========
  {
    id: "psj1",
    name: "Pan Francés (6 unidades)",
    description: "Pan del día anterior, perfecto para desayuno.",
    price: 2.00,
    originalPrice: 5.00,
    category: "Panadería",
    image: "https://img-global.cpcdn.com/recipes/403023df5ce8e8ea/680x781f0.5_0.50125_1.0q80/pan-frances-peruano-foto-principal.jpg",
    district: "El Agustino",
    businessName: "Panadería San José",
    expiresInHours: 18
  },
  {
    id: "psj2",
    name: "Croissant (4 unidades)",
    description: "Croissants hojaldrados con mantequilla. Del día anterior.",
    price: 3.50,
    originalPrice: 8.00,
    category: "Panadería",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=1200&auto=format&fit=crop",
    district: "El Agustino",
    businessName: "Panadería San José",
    expiresInHours: 16
  },
  {
    id: "psj3",
    name: "Pan Integral (8 unidades)",
    description: "Pan saludable de granos enteros. Horneado ayer.",
    price: 2.50,
    originalPrice: 6.00,
    category: "Panadería",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1200&auto=format&fit=crop",
    district: "El Agustino",
    businessName: "Panadería San José",
    expiresInHours: 20
  },
  {
    id: "psj4",
    name: "Empanadas de Manjar (6 unidades)",
    description: "Empanadas dulces rellenas de manjar blanco. Del día anterior.",
    price: 4.00,
    originalPrice: 9.00,
    category: "Panadería",
    image: "https://aprende.guatemala.com/wp-content/uploads/2016/10/pasos-para-hacer-empanadas-de-manjar-de-leche-en-Guatemala.webp",
    district: "El Agustino",
    businessName: "Panadería San José",
    expiresInHours: 15
  },
  {
    id: "psj5",
    name: "Pan con Chicharrón",
    description: "Pan fresco relleno de chicharrón. Del mediodía.",
    price: 3.90,
    originalPrice: 9.00,
    category: "Panadería",
    image: "https://comedera.com/wp-content/uploads/sites/9/2022/07/Pan-con-chicharron-limeno-shutterstock_1842217396.jpg",
    district: "El Agustino",
    businessName: "Panadería San José",
    expiresInHours: 5
  },
  
  // ========== Restaurant El Sabor de Casa - Ate (5 platos) ==========
  {
    id: "rsc1",
    name: "Tallarín Saltado",
    description: "Tallarines con verduras y pollo.",
    price: 7.90,
    originalPrice: 18.00,
    category: "Comidas",
    image: "https://comidaperuanaweb.org/wp-content/uploads/2018/10/Receta-de-Tallarines-Saltado-de-Pollo-Carne-1-1.jpg",
    district: "Ate",
    businessName: "Restaurant El Sabor de Casa",
    expiresInHours: 3
  },
  {
    id: "rsc2",
    name: "Carapulcra con Sopa Seca",
    description: "Plato típico peruano con papa seca y cerdo. Del almuerzo.",
    price: 9.90,
    originalPrice: 24.00,
    category: "Comidas",
    image: "https://www.infobae.com/new-resizer/CqmhTZgJwwS2PXeB0SKFEYf1DE0=/arc-anglerfish-arc2-prod-infobae/public/7XZCOUT7AZDKNOJRTSO5SBNGLI.jpg",
    district: "Ate",
    businessName: "Restaurant El Sabor de Casa",
    expiresInHours: 5
  },
  {
    id: "rsc3",
    name: "Bistec a lo Pobre",
    description: "Bistec con huevo, plátano y papas fritas. Preparado hoy.",
    price: 10.50,
    originalPrice: 25.00,
    category: "Comidas",
    image: "https://tofuu.getjusto.com/orioneat-local/resized2/cqdXfog3vwjr268NT-1459-x.webp",
    district: "Ate",
    businessName: "Restaurant El Sabor de Casa",
    expiresInHours: 4
  },
  {
    id: "rsc4",
    name: "Mondonguito a la Italiana",
    description: "Guiso tradicional con papa y hierbas. Del día.",
    price: 8.50,
    originalPrice: 20.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9a4jmDG9FCYtVYHX4HJLLRTKg2otVRCweVQ&s",
    district: "Ate",
    businessName: "Restaurant El Sabor de Casa",
    expiresInHours: 6
  },
  {
    id: "rsc5",
    name: "Escabeche de Pollo",
    description: "Pollo en salsa de cebolla y ají.",
    price: 7.50,
    originalPrice: 18.00,
    category: "Comidas",
    image: "https://jameaperu.com/assets/images/escabeche-de-pollo_800x534.webp",
    district: "Ate",
    businessName: "Restaurant El Sabor de Casa",
    expiresInHours: 2
  },
  
  // ========== Empanadas Argentinas - Santa Anita (4 platos) ==========
  {
    id: "ea1",
    name: "Empanadas de Carne (4 unidades)",
    description: "Empanadas de carne recién horneadas. Cierre de tienda.",
    price: 4.00,
    originalPrice: 10.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq1b3xdEnw-vy92rBIzFCENHmKBbpUaz9D6Q&s",
    district: "Santa Anita",
    businessName: "Empanadas Argentinas",
    expiresInHours: 2
  },
  {
    id: "ea2",
    name: "Empanadas de Pollo (4 unidades)",
    description: "Empanadas de pollo con especias. Horneadas hoy.",
    price: 3.80,
    originalPrice: 9.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtI0Xy_Aus-gUo2it1Wbl9i2X1AN4FijUcGQ&s",
    district: "Santa Anita",
    businessName: "Empanadas Argentinas",
    expiresInHours: 3
  },
  {
    id: "ea3",
    name: "Empanadas de Queso (4 unidades)",
    description: "Empanadas de queso derretido. Vegetarianas.",
    price: 3.50,
    originalPrice: 8.50,
    category: "Comidas",
    image: "https://i.ytimg.com/vi/RKZrqSeSXEE/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA2wr8xqXSJ-2cCYBWDP5MYq8xqLA",
    district: "Santa Anita",
    businessName: "Empanadas Argentinas",
    expiresInHours: 4
  },
  {
    id: "ea4",
    name: "Empanadas Mixtas (8 unidades)",
    description: "Variedad de empanadas de carne, pollo y queso. Del día.",
    price: 7.50,
    originalPrice: 18.00,
    category: "Comidas",
    image: "https://www.vekia.com.pe/cdn/shop/products/27_3751x.jpg?v=1596910373",
    district: "Santa Anita",
    businessName: "Empanadas Argentinas",
    expiresInHours: 5
  },
  
  // ========== Burger House - San Martin de Porres (5 platos) ==========
  {
    id: "bh1",
    name: "Hamburguesa Clásica",
    description: "Hamburguesa con carne, queso, lechuga y tomate.",
    price: 6.50,
    originalPrice: 15.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSddjpE64jVcMqw9x270i2vfbklSHIt-LzP7w&s",
    district: "San Martin de Porres",
    businessName: "Burger House",
    expiresInHours: 1
  },
  {
    id: "bh2",
    name: "Hamburguesa Doble",
    description: "Doble carne con queso cheddar y tocino.",
    price: 9.90,
    originalPrice: 22.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=1200&auto=format&fit=crop",
    district: "San Martin de Porres",
    businessName: "Burger House",
    expiresInHours: 2
  },
  {
    id: "bh3",
    name: "Hot Dog Especial",
    description: "Hot dog con salsas variadas y papas. Del turno de tarde.",
    price: 5.50,
    originalPrice: 12.00,
    category: "Comidas",
    image: "https://www.vvsupremo.com/wp-content/uploads/2016/02/900X570_Mexican-Style-Hot-Dogs.jpg",
    district: "San Martin de Porres",
    businessName: "Burger House",
    expiresInHours: 3
  },
  {
    id: "bh4",
    name: "Papas Fritas Grandes",
    description: "Papas fritas crujientes con salsa. Para compartir.",
    price: 3.90,
    originalPrice: 9.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwiB9W-DIUUOmdzL7GtS2b62J3Q8tQLPrk5w&s",
    district: "San Martin de Porres",
    businessName: "Burger House",
    expiresInHours: 2
  },
  {
    id: "bh5",
    name: "Onion Rings",
    description: "Aros de cebolla rebozados y fritos. Aperitivo crujiente.",
    price: 4.50,
    originalPrice: 10.00,
    category: "Comidas",
    image: "https://preppykitchen.com/wp-content/uploads/2025/04/Onion-Rings-Recipe-Card.jpg",
    district: "San Martin de Porres",
    businessName: "Burger House",
    expiresInHours: 1
  },
  
  // ========== Sabores de Lima - Independencia (4 platos) ==========
  {
    id: "sdl1",
    name: "Causa Limeña",
    description: "Tradicional causa rellena de pollo. Del almuerzo de hoy.",
    price: 5.90,
    originalPrice: 14.00,
    category: "Comidas",
    image: "https://recetasdecocina.elmundo.es/wp-content/uploads/2025/09/causa-limena-1024x683.jpg",
    district: "Independencia",
    businessName: "Sabores de Lima",
    expiresInHours: 4
  },
  {
    id: "sdl2",
    name: "Papa a la Huancaína",
    description: "Papas con salsa de ají amarillo cremosa. Entrada tradicional.",
    price: 4.50,
    originalPrice: 10.00,
    category: "Comidas",
    image: "https://img-global.cpcdn.com/recipes/9dcae0fe27a4c7ec/1200x630cq80/photo.jpg",
    district: "Independencia",
    businessName: "Sabores de Lima",
    expiresInHours: 6
  },
  {
    id: "sdl3",
    name: "Ocopa Arequipeña",
    description: "Papas con salsa de huacatay y maní. Del día.",
    price: 5.50,
    originalPrice: 12.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2k9ZTQ6PisNJnUeyRVzXvv_zNNbkppAaK4w&s",
    district: "Independencia",
    businessName: "Sabores de Lima",
    expiresInHours: 5
  },
  {
    id: "sdl4",
    name: "Tamal Criollo (2 unidades)",
    description: "Tamales de pollo envueltos en hoja de plátano. Hechos hoy.",
    price: 6.50,
    originalPrice: 15.00,
    category: "Comidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpWF0Hw2vSsIQcfCrWUOrg2Fa8pkqru1wQ1A&s",
    district: "Independencia",
    businessName: "Sabores de Lima",
    expiresInHours: 8
  },
  
  // ========== Jugos Naturales Tropical - Comas (5 bebidas) ==========
  {
    id: "jnt1",
    name: "Jugo de Papaya",
    description: "Jugo natural de papaya fresca.",
    price: 3.50,
    originalPrice: 8.00,
    category: "Bebidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5f_NfPtPWKy6xnssw3Az-8MtEyG0ohiUTAg&s",
    district: "Comas",
    businessName: "Jugos Naturales Tropical",
    expiresInHours: 2
  },
  {
    id: "jnt2",
    name: "Jugo de Fresa",
    description: "Refrescante jugo de fresas naturales. Del día.",
    price: 4.00,
    originalPrice: 9.00,
    category: "Bebidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrKlpFXtOyqwesNlmWlVHovafPwAzxRzx0xQ&s",
    district: "Comas",
    businessName: "Jugos Naturales Tropical",
    expiresInHours: 3
  },
  {
    id: "jnt3",
    name: "Jugo de Piña",
    description: "Jugo de piña dulce y natural. Refrescante.",
    price: 3.50,
    originalPrice: 8.00,
    category: "Bebidas",
    image: "https://imag.bonviveur.com/zumo-de-pina.jpg",
    district: "Comas",
    businessName: "Jugos Naturales Tropical",
    expiresInHours: 2
  },
  {
    id: "jnt4",
    name: "Jugo Mixto Tropical",
    description: "Combinación de frutas tropicales. Energizante.",
    price: 4.50,
    originalPrice: 10.00,
    category: "Bebidas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwRbfgVh4WqUpWb27BgvEpZlSBpVTvyZ97_w&s",
    district: "Comas",
    businessName: "Jugos Naturales Tropical",
    expiresInHours: 3
  },
  {
    id: "jnt5",
    name: "Smoothie de Mango",
    description: "Smoothie cremoso de mango con leche. Del día.",
    price: 5.50,
    originalPrice: 12.00,
    category: "Bebidas",
    image: "https://www.goodnes.com/sites/g/files/jgfbjl321/files/srh_recipes/50bc35dd2212868d66ebc7cff0e618c0.jpg",
    district: "Comas",
    businessName: "Jugos Naturales Tropical",
    expiresInHours: 4
  },
  
  // ========== Dulcería Tradición - Los Olivos (4 postres) ==========
  {
    id: "dt1",
    name: "Mazamorra Morada",
    description: "Postre tradicional de maíz morado. Hecho ayer.",
    price: 3.50,
    originalPrice: 8.00,
    category: "Postres",
    image: "https://comedera.com/wp-content/uploads/sites/9/2022/06/Mazamorra-morada-shutterstock_1530917543.jpg",
    district: "Los Olivos",
    businessName: "Dulcería Tradición",
    expiresInHours: 12
  },
  {
    id: "dt2",
    name: "Arroz con Leche",
    description: "Cremoso arroz con leche y canela. Del día anterior.",
    price: 3.50,
    originalPrice: 8.00,
    category: "Postres",
    image: "https://www.goodnes.com/sites/g/files/jgfbjl321/files/srh_recipes/8b80d005d2b35d7a583470e3f19c9c1f.jpeg",
    district: "Los Olivos",
    businessName: "Dulcería Tradición",
    expiresInHours: 10
  },
  {
    id: "dt3",
    name: "Picarones (6 unidades)",
    description: "Picarones de zapallo con miel de chancaca. Hechos hoy.",
    price: 4.50,
    originalPrice: 10.00,
    category: "Postres",
    image: "https://www.peru.travel/Contenido/General/Imagen/es/301/1.1/picarones.jpg",
    district: "Los Olivos",
    businessName: "Dulcería Tradición",
    expiresInHours: 6
  },
  {
    id: "dt4",
    name: "Turrón de Doña Pepa",
    description: "Dulce tradicional de octubre. Hecho artesanalmente.",
    price: 5.90,
    originalPrice: 13.00,
    category: "Postres",
    image: "https://mojo.generalmills.com/api/public/content/b4ScypOkiEunKKmVYEjZ7g_gmi_hi_res_jpeg.jpeg?v=507b6725&t=16e3ce250f244648bef28c5949fb99ff",
    district: "Los Olivos",
    businessName: "Dulcería Tradición",
    expiresInHours: 24
  },
  
  // ========== Café Express - Ate (4 platos) ==========
  {
    id: "ce1",
    name: "Sandwich Mixto (3 unidades)",
    description: "Sandwiches de jamón, queso y vegetales. Del día anterior.",
    price: 5.00,
    originalPrice: 12.00,
    category: "Comidas",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=1200&auto=format&fit=crop",
    district: "Ate",
    businessName: "Café Express",
    expiresInHours: 8
  },
  {
    id: "ce2",
    name: "Café Americano Grande",
    description: "Café recién pasado tamaño grande. Del turno de mañana.",
    price: 2.50,
    originalPrice: 6.00,
    category: "Bebidas",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=1200&auto=format&fit=crop",
    district: "Ate",
    businessName: "Café Express",
    expiresInHours: 4
  },
  {
    id: "ce3",
    name: "Muffin de Chocolate (3 unidades)",
    description: "Muffins esponjosos de chocolate. Horneados ayer.",
    price: 3.50,
    originalPrice: 8.00,
    category: "Postres",
    image: "https://www.clarin.com/2018/07/12/HkXoqEBmX_600x600__1.jpg",
    district: "Ate",
    businessName: "Café Express",
    expiresInHours: 15
  },
  {
    id: "ce4",
    name: "Combo Desayuno",
    description: "Café + sandwich + jugo. Perfecto para empezar el día.",
    price: 6.90,
    originalPrice: 16.00,
    category: "Comidas",
    image: "https://tofuu.getjusto.com/orioneat-local/resized2/a5AxJ2SnFPdcP9Ssc-2400-x.webp",
    district: "Ate",
    businessName: "Café Express",
    expiresInHours: 4
  }
];
